project:
  type: website
  output-dir: "."

website:
  title: "pasta_projeto_grupo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre
      - href: final.qmd
        text: Apresentação Final

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



