project:
  type: website
  output-dir: "."

website:
  title: "pasta_projeto_grupo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - index3.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



